# Generated by Django 4.1.4 on 2022-12-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='aga',
            new_name='age',
        ),
    ]
